### ISSUE TITLE
libconstrained_ik_plugin.so: undefined symbol

### ISSUE THREAD

**Issue by daichengkai** [ros-industrial-attic/industrial_moveit#19]
I followed the tutorial to add constrained_ik to my moveit_config and it works fine with the demo.launch. But when I want to use the ik_solver to my own package(like calling setFromIK function), error occurs and it said that 

/home/xxx/Imitation/devel/lib/IKPlan/load_model: symbol lookup error: /home/xxx/Imitation/devel/lib//libconstrained_ik_plugin.so: undefined symbol: _ZN2tf12poseMsgToKDLERKN13geometry_msgs5Pose_ISaIvEEERN3KDL5FrameE  

Can someone tells me how to do the right configuration in a new package when you want to use the constrained_ik_solver.

**Comment by Levi-Armstrong** [comment]
@DAIChengkai, Have you created your own constrained_ik moveit plugin or are you using constrained_ik/ConstrainedIKPlugin?

**Comment by Levi-Armstrong** [comment]
@DAIChengkai, It appears to not find tf::poseMsgToKDL and I noticed that tf_conversions is not included in the find_package function in the Industrial_moveit/constrained_ik/CMakelist.txt. Try adding it and see if it resolves the issue.

find_package(catkin REQUIRED COMPONENTS kdl_parser roscpp urdf eigen_conversions moveit_ros_planning moveit_core dynamic_reconfigure **tf_conversions**)

**Comment by Levi-Armstrong** [comment]
@DAIChengkai, I was able to determine that the libconstrained_ik_plugin.so does have undefined symbols using 

> $ ldd -d -r libconstrained_ik_plugin.so

At the end of the output I found:

> undefined symbol:   _ZN2tf12poseMsgToKDLERKN13geometry_msgs5Pose_ISaIvEEERN3KDL5FrameE    (./libconstrained_ik_plugin.so)
> undefined symbol: _ZN2tf12poseKDLToMsgERKN3KDL5FrameERN13geometry_msgs5Pose_ISaIvEEE    (./libconstrained_ik_plugin.so)

After adding the **tf_conversions** as described in my previous comment and recompiling the code. I then ran the _$ ldd -d -r libconstrained_ik_plugin.so_ and it was no longer undefined. Based on the findings I would expect that this should resolve your issue. I will submit a pull request to fix the issue once you verify that it fixes the issue.

**Comment by daichengkai** [comment]
@Levi-Armstrong problem solved! all works fine after adding the tf_conversions. Thanks a lot!

**Comment by Levi-Armstrong** [comment]
Glade to see it solved the issue.

**Comment by shaun-edwards** [comment]
@Levi-Armstrong, can this be closed?

**Comment by Levi-Armstrong** [comment]
@shaun-edwards, yep
