### ISSUE TITLE
STOMP ur_driver velocities

### ISSUE THREAD

**Issue by rcj86** [ros-industrial-attic/industrial_moveit#22]
I'm testing the STOMP planner with an UR5 real robot. I replaced OMPL by STOMP and works fine in simulation mode, but when I try to move the real robot, it doesn't move because only send positions, not velocities and accelerations.

**Comment by jrgnicho** [comment]
@rcj86 thanks for your feedback.  How did you verify that only positions are populated? Did you by any chance run the command below to see what is in the trajectory?

```
rostopic echo -n 1 /joint_path_command
```

**Comment by rcj86** [comment]
Sorry for my late reply. I looked in the topic /follow_joint_trajectory/goal and only positions are send, velocities and accelerations are empty. But if I change to OMPL, the robot execute the trajectory and sends velocities and accelerations.

OMPL:
![ompl](https://cloud.githubusercontent.com/assets/7824289/11238103/b11c0638-8de3-11e5-970a-5d62e416821f.png)

STOMP:
![stomp](https://cloud.githubusercontent.com/assets/7824289/11238104/b11ecc1a-8de3-11e5-9794-80fd6180b693.png)

Also I run the command rostopic echo -n 1 /joint_path_command, but I only saw this

WARNING: topic [rostopic echo -n 1 /joint_path_command] does not appear to be published yet

**Comment by jrgnicho** [comment]
@rcj86 
Make sure that the stomp_planning_pipeline.launch file in your package contains the **AddTimeParametrization** planning adapter as shown below:

```
  <arg name="planning_adapters" value="default_planner_request_adapters/AddTimeParameterization
                                       default_planner_request_adapters/FixWorkspaceBounds
                                       default_planner_request_adapters/FixStartStateBounds
                                       default_planner_request_adapters/FixStartStateCollision
                                       default_planner_request_adapters/FixStartStatePathConstraints" />
```

I verified that by adding this, the message in *\* /follow_joint_trajectory/goal*\* topic gets it's accelerations and velocities populated.
This adapter isn't listed in the stomp_test moveit package but I'll work on adding it there.  
@shaun-edwards this topic may be of interest to you.

**Comment by rcj86** [comment]
I added the AddTimeParametrization in the stomp_planning_pipeline.launch, and now I'm able to control the robot.

Thanks!!
