### ISSUE TITLE
STOMP Plans for my robot joint wheels

### ISSUE THREAD

**Issue by bbrito** [ros-industrial-attic/industrial_moveit#40]
I when I start stomp and do not move my robot stomp is able to fine nice plans. However if I move the robot it gives the following error:

[ERROR] [1493821272.310179796]: STOMP Start joint pose is out of bounds
[ERROR] [1493821272.310235237]: STOMP failed to get the start and goal positions

I search inside stomp_planner.cpp and this happens because it includes my joint wheel states in the planning. I don't know if I'm doing something wrong but this joints from the wheels do not belong to the planning group. I even defined them as passive in the robot srdf but it din't work out.

Is it stomp also take into account the planning of this joint or I am doing something wrong?

**Comment by jrgnicho** [comment]
Could you provide more details on how you are calling STOMP and which release you are using?
