### ISSUE TITLE
Joint Limits Checking

### ISSUE THREAD

**Issue by Jmeyer1292** [ros-industrial-attic/industrial_moveit#43]
I noticed a difference in behavior between OMPL and STOMP and thought you all might find it interesting:

I was getting the ```Start joint pose is out of bounds``` error that some other issues allude to. Using OMPL with the same planning requests produced no issues.

For me, I was using the `industrial_calibration` library which includes a set of 6 "calibrate-able joints" for both the target and the camera I had on the end of a robot. Turned out the definition of these joints had a really small valid range, -1 to 1, and I had exceeded that limit.

So the moral is: **Stomp checks the ENTIRE start state for validity and OMPL only checks the active move group**.

**Comment by jrgnicho** [comment]
There's a PR #42  addressing this issue for the indigo branch
