### ISSUE TITLE
Using OMPL and STOMP at the same time

### ISSUE THREAD

**Issue by yijiangh** [ros-industrial-attic/industrial_moveit#66]
I'm wondering if we can load OMPL's planner, if STOMP fails to find a solution? In current tutorials, it seems like we can only specify one in the planning_pipeline configuration.

Thanks!

**Comment by gavanderhoorn** [comment]
This is a limitation currently in MoveIt. It only loads a single planner plugin.

It's technically possible to load multiple, but it just hasn't been implemented.

**Comment by Levi-Armstrong** [comment]
What we have done in the past is create a custom planning plugin which loads the stomp plugin and ompl plugin to accomplish what you want.

**Comment by yijiangh** [comment]
@Levi-Armstrong So do we need to have two separated move group to load these two plugins?

**Comment by Levi-Armstrong** [comment]
You should not.

**Comment by Levi-Armstrong** [comment]
Sorry just read this again, when you refer to move group is that robot move groups or move group nodes?

**Comment by yijiangh** [comment]
@Levi-Armstrong  Move group nodes.

**Comment by Levi-Armstrong** [comment]
If you create a custom plugin that incorporates the two then you should not need two move group nodes.

**Comment by yijiangh** [comment]
@Levi-Armstrong Just to make sure I understand it correctly: 

I need to create a customized `planning_interface` plugin like we did in [stomp_moveit](https://github.com/ros-industrial/industrial_moveit/blob/kinetic-devel/stomp_moveit/include/stomp_moveit/stomp_planner_manager.h) and incorporate functions to call different planners, so we can tell the plugin which planner it should use (e.g. through a `SetPlanner(string)` function) when it takes `moveit_msgs::MotionPlanRequest`? Am I right?

**Comment by Levi-Armstrong** [comment]
That is correct.

**Comment by yijiangh** [comment]
Thanks for your feedback @Levi-Armstrong @gavanderhoorn . 

Then I think it's proper to close this issue since the resolution is not directly related to STOMP.

**Comment by gavanderhoorn** [comment]
I've implemented something similar to what @Levi-Armstrong describes some time ago. I'll see if I can get that in a state that I can push it somewhere.

It's not that exciting really: create a planner plugin taht essentially loads other planning plugins and then implement *some way* for moveit clients to indicate which planning plugin they would like to use.

I went with a plugin prefix, so planning requests would specify something like `ompl/SBLkConfigDefault`. The multi-planner plugin planning plugin (yeah ..) figures out the prefix and forwards the request to whichever planning plugin was registered for that prefix.

**Comment by yijiangh** [comment]
@gavanderhoorn 

> I've implemented something similar to what @Levi-Armstrong describes some time ago. I'll see if I can get that in a state that I can push it somewhere.

It'd be fantastic if you could share your previous work!

> I went with a plugin prefix, so planning requests would specify something like ompl/SBLkConfigDefault. The multi-planner plugin planning plugin (yeah ..) figures out the prefix and forwards the request to whichever planning plugin was registered for that prefix.

I agree. Specifying something like `primary planning plugin` and `secondary planning plugin` in a config file. Then the multi-planner plugin loads them and forwards the request accordingly.

**Comment by gavanderhoorn** [comment]
@yijiangh: see [gavanderhoorn/moveit_mpp](https://github.com/gavanderhoorn/moveit_mpp).

Note that this treats all plugins as equal. Choosing one over another is left to the client.

**Comment by yijiangh** [comment]
@gavanderhoorn Thank you so much! Really appreciate it.
