### ISSUE TITLE
"Jerky" motions while using kuka_rsi_hw_interface for a KUKA KR240 L210 MED

### ISSUE THREAD

**Issue by BastiSta** [ros-industrial-attic/industrial_moveit#79]
Hi everybody,
I am working with a KUKA KR240 L210 MED with a safe control system and would like to control it via the kuka_rsi_hw_interface. Starting the moveit_planning_execution.launch works and the robot can be started without problems. Also the visualization and path planning via Rviz and the execution of the movement works. My problem now is that the robot jerks randomly and does not move smoothly. At first I thought, there are too few waypoints passed and increased the number but there was no improvement. Also different planners from moveit don't lead to a clear improvement of the movement. 
Has someone already had similar problems and could help me?

**Comment by gavanderhoorn** [comment]
I'm going to close this issue here as I'm not sure this tracker is an appropriate one to discuss this.

This also seems to have been cross-posted to https://github.com/ros-industrial/kuka_experimental/issues/147.

If you feel otherwise @BastiSta please re-open and clarify.
